server:
  port: 90


spring:
  elasticsearch:
    rest:
      uris: 43.139.206.205:9200
  datasource:
    url: jdbc:mysql://localhost:3306/java-plateform?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 217812.com
  application:
    name: plate-from-app
  redis:
    port: 6379
    password: 217812.com
    host: 43.139.206.205
    lettuce:
      pool:
        max-idle: 38
        min-idle: 0
        max-active: 8
        max-wait: -1
      shutdown-timeout: 320
  rabbitmq:
    host: 43.139.206.205
    port: 5672
    username: admin
    password: admin

#邮箱发送验证码配置
msm:
  email: 2178127391@qq.com
  host: smtp.qq.com
  port: 587
  password: qrmkqrccuawpebii

#文件上传配置
fdfs:
  # 连接超时时间
  connect-timeout: 30000
  # 读取时间
  so-timeout: 30000
  # tracker服务配置地址列表
  tracker-list: 43.139.206.205:22122

#阿里云
aliyvn:
  accesskeyId: LTAI5tRF5zmXhxzYP6SEmsFg
  accesskeySecret: bGYVhdrhuJWAhAiVdwcastgLRqNB9Y
  endpoint: imageaudit.cn-shanghai.aliyuncs.com
