server:
  port: 90
spring:
  elasticsearch:
    rest:
      uris: localhost:9200
  datasource:
    url: jdbc:mysql://localhost:3306/java-plateform?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: #数据库密码
  application:
    name: plate-from-app
  redis:
    port: 6379
    password: #redis密码
    host: localhost
    lettuce:
      pool:
        max-idle: 38
        min-idle: 0
        max-active: 8
        max-wait: -1
      shutdown-timeout: 320
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: #mq密码

#邮箱发送验证码配置
msm:
  email: #邮箱号
  host: smtp.qq.com
  port: 587
  password: #密码

#文件上传配置
fdfs:
  # 连接超时时间
  connect-timeout: 30000
  # 读取时间
  so-timeout: 30000
  # tracker服务配置地址列表
  tracker-list: localhost:22122

#阿里云
aliyvn:
  accesskeyId: #案例与keyID
  accesskeySecret: #阿里云密钥
  endpoint: imageaudit.cn-shanghai.aliyuncs.com
